### ISSUE TITLE
No related posts were found. Check the index.

### ISSUE THREAD

**Issue by giancta92** [danecando/jquery.ghostrelated#8]
Hello, can you help me please? I am getting the following message:
"No related posts were found. Check the index."
My version of ghost is 0.7. The theme I'm using is "anima" http://themeforest.net/item/anima-responsive-pet-rescue-and-shelter-template/11172622

This is my web http://tecneofito.com.

**Comment by danecando** [comment]
Do you have any posts with the same tag as the one you're viewing?

**Comment by giancta92** [comment]
Yes, there are more posts with the same tag.

**Comment by danecando** [comment]
@giancta92 can you link a paste to your config and markup

**Comment by giancta92** [comment]
Hi, excuse me, Where can I get this information?

**Comment by sodbileg** [comment]
@giancta92 Make sure your `titleClass` and `tagsClass` are correct.
